<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                  ->prependFile($this->basePath() . '/js/core.js')
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>
    
<!--<script src="http://connect.facebook.net/en_US/all.js"></script>-->
  </head>

  <body>
      <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '365454110216217', // App ID
            channelUrl : '//connect.facebook.net/en_US/all.js', // Channel File
            status     : true, // check login status
            cookie     : true, // enable cookies to allow the server to access the session
            xfbml      : true  // parse XFBML
          });
          FB.api('/me', function(user) {
            if (user) {
              var image = document.getElementById('image');
              image.src = 'http://graph.facebook.com/' + user.id + '/picture';
              var name = document.getElementById('name');
              name.innerHTML = user.name
            }
          });
        };
       // Load the SDK Asynchronously
        (function(d){
           var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
           if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/en_US/all.js";
           ref.parentNode.insertBefore(js, ref);
         }(document));
         
         
         function login() {
           FB.getLoginStatus(function(response) {
            if (response.status === 'connected') {
              alert(1);
            } else if (response.status === 'not_authorized') {
              _login();
            } else {
              _login()
            }
           });
                
         }
         function _login(){
             FB.login(function(response) {
                    if (response.authResponse) {
                        testAPI();
                    } else {
                        // cancelled
                    }
                });
         }
         
         
         function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
        console.log('Good to see you, ' + response.name + '.');
    });
}
         
      </script>
      <a href="#" onclick="login();">login</a>
       <div align="center">
        <img id="image"/>
        <div id="name"></div>
      </div>
      
      
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php
         
          echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
          <div class="nav-collapse">
            <ul class="nav">
                
              <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Hot') ?></a></li>
              <li class="active"><a href="<?php echo $this->url('best') ?>"><?php echo $this->translate('Best') ?></a></li>
              <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('New') ?></a></li>
              <li class="active"><a href="<?php echo $this->url('stick') ?>"><?php echo $this->translate('Stick!') ?></a></li>
              
                
            </ul>
              <ul class="nav" style="float:right">
                  <li class="active"><?$this->user()->getMenuButton()?></li>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
<div class="row-fluid">
  <div class="span4">aaaa</div>
  <div class="span8">bbbb</div>
</div>
      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
